language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  api_key:
    secure: iYc5RFU5bf3qnbRyvNsiltos/MdVCmODFZ9s3I07K2aTU1SHEjukxdBiD21WT3IEuJLWT3cr5PneL4Rcs3VESNPDUkMS1bT6/cvk7O0kD9UvmauAkUnv/w1HGQiGd7MaMh/2OyE1+U2qXH6uRNKpHeohze9euT2AhEDHsNswWcmcBRGzhcM50MzbWq9pnct4v5cjJJVG3rvboYvnkYp5OQh8Hr8sFa3FsdJSHhQCT342MU/JrNIjlYQWB/taH9viagoIXs9f9uIBLjAglvYPSn4AEXl8CXaMBLlNpJvPZELVecuT7AqUd4a0Jh48ZH5OONEjGFXlNwLKAdBb+mtLptxCH1lvtW36q4V+lT0TWDBVF0ypgR+kG8IzLAM6+iUv00OlQ2MbMtwFfT77HQrGBRW6BaFtlFWuXFYd7pmbEL8KecQgQYVaflgN7L5cqs9/oun1wLbqbSr061p7r2jL2zYAdyeG0swgWKwIs+v3JP08WmLECT7q331aZEQiDL/XpL4pm0gNfllN3qzRu8SYXvzF+mrnSXThZqGRNl2LWrW2xYTCtlTzejHxAhr21rggiqEYnmYMZGdKyabyitAUTOe1sMZnWdEpZjMp3EGiueEzWFQxAjU/fRVXzrzoNJNVMSKDgTJ7n2tGDm/WQ7/7OqKdO04qBfUdgRt5L0oxVTY=
