language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: iJNd3nyxNKGnP4Wozu2KHiO9Gtzi2bTtRlNIKqNbFTkW5BKARh79mSIO0JI5KXdIav68VvmXEsvWCJN2GugnPS3e9BpuTYGMXAry0E1fmVONXAldwO5+OUYUVXVKKr9EXZOUcq0eO9XuuRPMsWCSg3DSWYJNQi70vQ8xQLe0h6+9FWAuOCJAY4KKvQHROTnnLbxlcQwzmquRgMpv5EVGaFDFf5/yX3u2jTq6ZWEk28RnX+GuXbfaovzuOoLQrexlTeEZb6AXL/U5lvt/oRS5syUBcqB3MN1U8VLPMhqPk+eSGHhcm95+2L2cwaZavbOfcFplA4U5RP6PKni1zSIGykTO5JGOz+AJZoRoXqWDJCv2qcIRXmg2iFvO1UlFOXkp21m6Kw5D66HNw7mYaVZlDQkrFWmGKZzMo2hQmMZ+NTNJ+xvTT7VlnTNDRLSKmRrGRksGE1hZEhO04WZ3RKMJSnNNP7GSK5WeZ9vecnyeAVBhay7I5T3Rp9tDRbR4D7PbbYa5k+l0QucLbTBDjYZOVKpslhXeRcJkbHU4NlIRsWNk2loCvbqJSK5hO/i/fX+HzXKnBl5QOhjAlTFmra+G25UD6W8GKi5gKN6YylG+WOl7cjQRampO9ZmTmygAEsSsqOzu8mn2gH7nlchWLV7zckUYWBvLZWgJSJQWAt7+fF8=
  app: zhiquan
  on:
    repo: Ken-97/BasicWebApp
